### PR TITLE
Disability and disable visibility of show password feature

### PR DESCRIPTION
**Pull request by Michelle-Lohwt**

### CODE REVIEW

**Comment by YouQuan2007** [comment]
What is the purpose? disable the visibility of show password means?

**Comment by Michelle-Lohwt** [comment]
Disable is does not allow the user to write anything in the textPassword

Visible is to allow the user to see the textPassword

Originally, although it is not obvious, but since you might have problems in the showPassword button, I disable and hide the textPassword from user. 

But the problem of the thing that you have to click showPassword to login is also because of you choosing to use password instead of textPassword in your code.

So this disable and setting visibility is more like a double security to ensure users didn't accidentally enter password into the wrong field

**Comment by YouQuan2007** [comment]
okay understood, but my issue is already settled after i amended the code, so is this still needed?

**Comment by Michelle-Lohwt** [comment]
It serves as double security, for me is a yes, it depends how you all think

**Comment by YouQuan2007** [comment]
ya if it is for double security purposes then i think should be okay, how about @ziqiang2344 and @GitHubUser5136 ?

**Comment by ziqiang2344** [comment]
Suggest prioritizing the dashboard first according to its importance.

**Comment by YouQuan2007** [comment]
okay

**Review by YouQuan2007 — APPROVED** [review]

**Pull request merged**
